global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
  - job_name: 'ticketing'
    metrics_path: "API/actuator/prometheus"
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]